import '../../features/bazi/domain/bazi_chart.dart';

/// Ba Zi (四柱八字) Four Pillars of Destiny — offline calculation engine.
///
/// Pure Dart mirror of aestral-backend/src/bazi.ts.
/// Used as offline fallback when the Cloudflare Workers API is unreachable.
///
/// Algorithms:
/// - Year Pillar  : Li Chun (立春 ~Feb 4) solar boundary + 60-cycle
/// - Month Pillar : 12 Major Solar Terms (节 jié), approximate ±1 day
/// - Day Pillar   : JDN-based (reference: 1 Jan 2000 = Geng Chen)
/// - Hour Pillar  : 2-hour shi (時) blocks, Zi (子) starts at 23:00
/// - True Solar Time: longitude correction for Indonesia (WIB/WITA/WIT)
/// - Luck Pillars : 大運 8×10-year cycles from month pillar sequence

class BaziUtils {
  // ─── Heavenly Stems 天干 ────────────────────────────────────────────────

  static const List<String> stemIds = [
    'jia',
    'yi',
    'bing',
    'ding',
    'wu',
    'ji',
    'geng',
    'xin',
    'ren',
    'gui',
  ];

  static const List<String> stemSymbols = [
    '甲',
    '乙',
    '丙',
    '丁',
    '戊',
    '己',
    '庚',
    '辛',
    '壬',
    '癸',
  ];

  static const List<String> stemNamesId = [
    'Kayu Yang',
    'Kayu Yin',
    'Api Yang',
    'Api Yin',
    'Tanah Yang',
    'Tanah Yin',
    'Logam Yang',
    'Logam Yin',
    'Air Yang',
    'Air Yin',
  ];

  static const List<String> stemElements = [
    'kayu',
    'kayu',
    'api',
    'api',
    'tanah',
    'tanah',
    'logam',
    'logam',
    'air',
    'air',
  ];

  // ─── Earthly Branches 地支 ──────────────────────────────────────────────

  static const List<String> branchIds = [
    'zi',
    'chou',
    'yin',
    'mao',
    'chen',
    'si',
    'wu',
    'wei',
    'shen',
    'you',
    'xu',
    'hai',
  ];

  static const List<String> branchSymbols = [
    '子',
    '丑',
    '寅',
    '卯',
    '辰',
    '巳',
    '午',
    '未',
    '申',
    '酉',
    '戌',
    '亥',
  ];

  static const List<String> branchZodiacsId = [
    'Tikus',
    'Kerbau',
    'Harimau',
    'Kelinci',
    'Naga',
    'Ular',
    'Kuda',
    'Kambing',
    'Monyet',
    'Ayam',
    'Anjing',
    'Babi',
  ];

  static const List<String> branchElements = [
    'air',
    'tanah',
    'kayu',
    'kayu',
    'tanah',
    'api',
    'api',
    'tanah',
    'logam',
    'logam',
    'tanah',
    'air',
  ];

  // ─── 60-Pillar Sexagenary Cycle 六十甲子 ────────────────────────────────

  static const List<String> sexagenarySlugs = [
    'jia_zi',
    'yi_chou',
    'bing_yin',
    'ding_mao',
    'wu_chen',
    'ji_si',
    'geng_wu',
    'xin_wei',
    'ren_shen',
    'gui_you',
    'jia_xu',
    'yi_hai',
    'bing_zi',
    'ding_chou',
    'wu_yin',
    'ji_mao',
    'geng_chen',
    'xin_si',
    'ren_wu',
    'gui_wei',
    'jia_shen',
    'yi_you',
    'bing_xu',
    'ding_hai',
    'wu_zi',
    'ji_chou',
    'geng_yin',
    'xin_mao',
    'ren_chen',
    'gui_si',
    'jia_wu',
    'yi_wei',
    'bing_shen',
    'ding_you',
    'wu_xu',
    'ji_hai',
    'geng_zi',
    'xin_chou',
    'ren_yin',
    'gui_mao',
    'jia_chen',
    'yi_si',
    'bing_wu',
    'ding_wei',
    'wu_shen',
    'ji_you',
    'geng_xu',
    'xin_hai',
    'ren_zi',
    'gui_chou',
    'jia_yin',
    'yi_mao',
    'bing_chen',
    'ding_si',
    'wu_wu',
    'ji_wei',
    'geng_shen',
    'xin_you',
    'ren_xu',
    'gui_hai',
  ];

  // ─── Solar Term Lookup Table (节 Jié) ───────────────────────────────────
  // Day-of-month for each of the 12 jié, 1924–2100 (WIB UTC+7).
  // Generated by scripts/gen_solar_terms.js (Meeus algorithm).
  // Access: _jieDays[(year - 1924) * 12 + termIndex]
  // termIndex: 0=XiaoHan 1=LiChun 2=JingZhe 3=QingMing 4=LiXia  5=MangZhong
  //            6=XiaoShu 7=LiQiu  8=BaiLu   9=HanLu  10=LiDong 11=DaXue
  static const List<int> _jieDays = [
    6,
    5,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1924–1925
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8,
    6,
    5,
    6,
    6,
    6,
    7,
    8,
    8,
    8,
    9,
    8,
    8, // 1926–1927
    6,
    5,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1928–1929
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8,
    6,
    5,
    6,
    6,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1930–1931
    6,
    5,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1932–1933
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8,
    6,
    5,
    6,
    6,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1934–1935
    6,
    5,
    6,
    5,
    5,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1936–1937
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8,
    6,
    5,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1938–1939
    6,
    5,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 1940–1941
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1942–1943
    6,
    5,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 1944–1945
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1946–1947
    6,
    5,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 1948–1949
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1950–1951
    6,
    5,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 1952–1953
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1954–1955
    6,
    5,
    5,
    5,
    5,
    6,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7, // 1956–1957
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1958–1959
    6,
    5,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7, // 1960–1961
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1962–1963
    6,
    5,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7, // 1964–1965
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1966–1967
    6,
    5,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    8,
    8,
    8,
    7,
    7, // 1968–1969
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1970–1971
    6,
    5,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 1972–1973
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1974–1975
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 1976–1977
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    8,
    8,
    8,
    9,
    8,
    8, // 1978–1979
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 1980–1981
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1982–1983
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    7,
    8,
    7,
    7, // 1984–1985
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1986–1987
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 1988–1989
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1990–1991
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 1992–1993
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1994–1995
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 1996–1997
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    9,
    8,
    7, // 1998–1999
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2000–2001
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 2002–2003
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2004–2005
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    6,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 2006–2007
    6,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2008–2009
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 2010–2011
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    7,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2012–2013
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 2014–2015
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2016–2017
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    8,
    7, // 2018–2019
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2020–2021
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7, // 2022–2023
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2024–2025
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    6,
    6,
    7,
    8,
    8,
    8,
    7,
    7, // 2026–2027
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2028–2029
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 2030–2031
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2032–2033
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 2034–2035
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2036–2037
    5,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    6,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 2038–2039
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    7, // 2040–2041
    5,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    8,
    8,
    7,
    7, // 2042–2043
    6,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    7, // 2044–2045
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    6,
    7,
    7,
    7,
    8,
    7,
    7, // 2046–2047
    5,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6, // 2048–2049
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2050–2051
    5,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6, // 2052–2053
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2054–2055
    5,
    4,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    6,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6, // 2056–2057
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2058–2059
    5,
    4,
    5,
    4,
    5,
    5,
    6,
    6,
    7,
    7,
    6,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6, // 2060–2061
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    5,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2062–2063
    5,
    4,
    5,
    4,
    4,
    5,
    6,
    6,
    7,
    7,
    6,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6, // 2064–2065
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2066–2067
    5,
    4,
    5,
    4,
    4,
    5,
    6,
    6,
    7,
    7,
    6,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6, // 2068–2069
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2070–2071
    5,
    4,
    5,
    4,
    4,
    5,
    6,
    6,
    7,
    7,
    6,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6, // 2072–2073
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    7,
    5,
    4,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2074–2075
    5,
    4,
    5,
    4,
    4,
    5,
    6,
    6,
    7,
    7,
    6,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6, // 2076–2077
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    7,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2078–2079
    5,
    4,
    4,
    4,
    4,
    4,
    6,
    6,
    6,
    7,
    6,
    6,
    4,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6, // 2080–2081
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2082–2083
    5,
    4,
    4,
    4,
    4,
    4,
    6,
    6,
    6,
    7,
    6,
    6,
    4,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    7,
    6, // 2084–2085
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2086–2087
    5,
    4,
    4,
    4,
    4,
    4,
    6,
    6,
    6,
    7,
    6,
    6,
    4,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    7,
    6,
    6, // 2088–2089
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2090–2091
    5,
    4,
    4,
    4,
    4,
    4,
    6,
    6,
    6,
    7,
    6,
    6,
    4,
    3,
    5,
    4,
    4,
    5,
    6,
    6,
    7,
    7,
    6,
    6, // 2092–2093
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2094–2095
    5,
    4,
    4,
    4,
    4,
    4,
    6,
    6,
    6,
    7,
    6,
    6,
    4,
    3,
    5,
    4,
    4,
    5,
    6,
    6,
    7,
    7,
    6,
    6, // 2096–2097
    5,
    3,
    5,
    4,
    5,
    5,
    6,
    7,
    7,
    8,
    7,
    6,
    5,
    3,
    5,
    4,
    5,
    5,
    7,
    7,
    7,
    8,
    7,
    7, // 2098–2099
    5, 4, 5, 4, 5, 5, 7, 7, 7, 8, 7, 7, // 2100
  ];

  static const List<int> _jieNominal = [6, 4, 6, 5, 6, 6, 7, 7, 8, 8, 7, 7];

  // Cang Gan (藏干) — hidden stem indices per Earthly Branch.
  static const List<List<int>> _branchHiddenStems = [
    [9], // zi  (0, Rat)    : gui
    [5, 9, 7], // chou(1, Ox)     : ji, gui, xin
    [0, 2, 4], // yin (2, Tiger)  : jia, bing, wu
    [1], // mao (3, Rabbit) : yi
    [4, 1, 9], // chen(4, Dragon) : wu, yi, gui
    [2, 4, 6], // si  (5, Snake)  : bing, wu, geng
    [3, 5], // wu  (6, Horse)  : ding, ji
    [5, 3, 1], // wei (7, Goat)   : ji, ding, yi
    [6, 8, 4], // shen(8, Monkey) : geng, ren, wu
    [7], // you (9, Rooster): xin
    [4, 7, 3], // xu  (10, Dog)   : wu, xin, ding
    [8, 0], // hai (11, Pig)   : ren, jia
  ];

  /// Returns actual day-of-month for jié term [termIndex] in [year] (WIB).
  static int _getJieDay(int termIndex, int year) {
    if (year < 1924 || year > 2100) return _jieNominal[termIndex];
    return _jieDays[(year - 1924) * 12 + termIndex];
  }

  // ─── Core Utilities ─────────────────────────────────────────────────────

  /// Converts a Gregorian date to Julian Day Number.
  /// Identical to WetonUtils.dateToJdn — kept separate to avoid coupling.
  static int dateToJdn(int year, int month, int day) {
    int y = year;
    int m = month;
    if (m <= 2) {
      y -= 1;
      m += 12;
    }
    final int a = y ~/ 100;
    final int b = 2 - a + (a ~/ 4);
    return (365.25 * (y + 4716)).toInt() +
        (30.6001 * (m + 1)).toInt() +
        day +
        b -
        1524;
  }

  /// Returns 0-indexed position (0–59) in the sexagenary cycle.
  /// Uses the Chinese Remainder Theorem: solve p ≡ s (mod 10), p ≡ b (mod 12).
  static int _sexagenaryIndex(int stemIndex, int branchIndex) {
    final int diff = ((branchIndex - stemIndex) % 12 + 12) % 12;
    final int k = (((diff ~/ 2) * 5) % 6 + 6) % 6;
    return (stemIndex + 10 * k) % 60;
  }

  /// Assembles a BaziPillar from stem and branch indices.
  static BaziPillar _buildPillar(int stemIndex, int branchIndex) {
    final int cycleIdx = _sexagenaryIndex(stemIndex, branchIndex);
    return BaziPillar(
      id: sexagenarySlugs[cycleIdx],
      stemId: stemIds[stemIndex],
      branchId: branchIds[branchIndex],
      stemIndex: stemIndex,
      branchIndex: branchIndex,
      stemSymbol: stemSymbols[stemIndex],
      branchSymbol: branchSymbols[branchIndex],
      stemNameId: stemNamesId[stemIndex],
      branchZodiacId: branchZodiacsId[branchIndex],
      element: stemElements[stemIndex],
    );
  }

  // ─── True Solar Time ────────────────────────────────────────────────────

  /// Corrects local standard time to True Solar Time using longitude.
  /// Indonesia: WIB (105°), WITA (120°), WIT (135°).
  static ({int hour, int minute, double offsetMinutes}) applyTrueSolarTime(
    int localHour,
    int localMinute,
    double longitude,
  ) {
    final double standardMeridian = (longitude / 15).round() * 15.0;
    final double offsetMinutes = (longitude - standardMeridian) * 4.0;
    final double totalMinutes = localHour * 60 + localMinute + offsetMinutes;
    final double normalised = ((totalMinutes % 1440) + 1440) % 1440;
    return (
      hour: normalised ~/ 60,
      minute: normalised
          .remainder(60)
          .floor(), // W32: .round() could produce 60 on x.5 values
      offsetMinutes: offsetMinutes,
    );
  }

  // ─── Pillar Calculations ────────────────────────────────────────────────

  /// Year Pillar — Li Chun (立春) boundary from lookup table, not fixed Feb 4.
  static BaziPillar getYearPillar(int year, int month, int day) {
    final int liChunDay = _getJieDay(1, year); // index 1 = Li Chun
    final int adjustedYear = (month < 2 || (month == 2 && day < liChunDay))
        ? year - 1
        : year;
    final int stemIndex = ((adjustedYear - 4) % 10 + 10) % 10;
    final int branchIndex = ((adjustedYear - 4) % 12 + 12) % 12;
    return _buildPillar(stemIndex, branchIndex);
  }

  /// Returns the Earthly Branch index for the Ba Zi month containing the date.
  /// Uses actual solar term day for [year] (not fixed approximation).
  static int _monthBranchIndex(int month, int day, int year) {
    final int md = month * 100 + day;
    if (md < 100 + _getJieDay(0, year)) return 0; // < XiaoHan : Rat
    if (md < 200 + _getJieDay(1, year)) return 1; // < LiChun  : Ox
    if (md < 300 + _getJieDay(2, year)) return 2; // < JingZhe : Tiger
    if (md < 400 + _getJieDay(3, year)) return 3; // < QingMing: Rabbit
    if (md < 500 + _getJieDay(4, year)) return 4; // < LiXia   : Dragon
    if (md < 600 + _getJieDay(5, year)) return 5; // < MangZhong: Snake
    if (md < 700 + _getJieDay(6, year)) return 6; // < XiaoShu : Horse
    if (md < 800 + _getJieDay(7, year)) return 7; // < LiQiu   : Goat
    if (md < 900 + _getJieDay(8, year)) return 8; // < BaiLu   : Monkey
    if (md < 1000 + _getJieDay(9, year)) return 9; // < HanLu   : Rooster
    if (md < 1100 + _getJieDay(10, year)) return 10; // < LiDong  : Dog
    if (md < 1200 + _getJieDay(11, year)) return 11; // < DaXue   : Pig
    return 0; // DaXue+   : Rat
  }

  /// Month Pillar — branch from solar term, stem from year stem.
  static BaziPillar getMonthPillar(
    int month,
    int day,
    int yearStemIndex,
    int year,
  ) {
    final int monthBranchIndex = _monthBranchIndex(month, day, year);
    final int tigerStemStart = (yearStemIndex % 5) * 2 + 2;
    final int monthSequence = (monthBranchIndex - 2 + 12) % 12;
    final int monthStemIndex = (tigerStemStart + monthSequence) % 10;
    return _buildPillar(monthStemIndex, monthBranchIndex);
  }

  /// Day Pillar — JDN reference: 1 Jan 2000 = Geng (6) Chen (4).
  static BaziPillar getDayPillar(int year, int month, int day) {
    final int jdn = dateToJdn(year, month, day);
    final int stemIndex = ((jdn - 2451545 + 6) % 10 + 10) % 10;
    final int branchIndex = ((jdn - 2451545 + 4) % 12 + 12) % 12;
    return _buildPillar(stemIndex, branchIndex);
  }

  /// Hour Pillar — 12 two-hour shi blocks, Zi starts at 23:00.
  static BaziPillar getHourPillar(int hour, int dayStemIndex) {
    final int hourBranchIndex = ((hour + 1) % 24) ~/ 2;
    final int stemStart = (dayStemIndex % 5) * 2;
    final int hourStemIndex = (stemStart + hourBranchIndex) % 10;
    return _buildPillar(hourStemIndex, hourBranchIndex);
  }

  // ─── Wu Xing Balance ────────────────────────────────────────────────────

  /// Counts elemental distribution across stems, branch surfaces, and
  /// Cang Gan (藏干 hidden stems). A full chart yields 16–17 characters.
  static WuXingBalance calculateWuXingBalance(List<BaziPillar?> pillars) {
    int kayu = 0, api = 0, tanah = 0, logam = 0, air = 0;

    void addElement(String el, {int weight = 1}) {
      switch (el) {
        case 'kayu':
          kayu += weight;
          break;
        case 'api':
          api += weight;
          break;
        case 'tanah':
          tanah += weight;
          break;
        case 'logam':
          logam += weight;
          break;
        case 'air':
          air += weight;
          break;
      }
    }

    // Cang Gan weight: main qi=3, middle qi=2, residual qi=1
    int _cangGanWeight(int position, int total) {
      if (total == 1) return 3;
      if (total == 2) return position == 0 ? 3 : 1;
      return 3 - position; // 3, 2, 1
    }

    for (final pillar in pillars) {
      if (pillar == null) continue;
      // Heavenly Stem
      addElement(stemElements[pillar.stemIndex]);
      // Earthly Branch surface element
      addElement(branchElements[pillar.branchIndex]);
      // Cang Gan — weighted: main qi +3, middle qi +2, residual qi +1
      final hiddenList = _branchHiddenStems[pillar.branchIndex];
      for (int i = 0; i < hiddenList.length; i++) {
        addElement(
          stemElements[hiddenList[i]],
          weight: _cangGanWeight(i, hiddenList.length),
        );
      }
    }

    return WuXingBalance(
      kayu: kayu,
      api: api,
      tanah: tanah,
      logam: logam,
      air: air,
    );
  }

  // ─── Main Entry Point ───────────────────────────────────────────────────

  /// Calculates a complete Ba Zi chart offline.
  ///
  /// [birthDate]  — DateTime of birth (only date components used)
  /// [birthHour]  — Local standard time hour (0–23), null if unknown
  /// [longitude]  — Decimal degrees, used for True Solar Time correction
  static BaziChart calculateBaziChart(
    DateTime birthDate, {
    int? birthHour,
    double? longitude,
  }) {
    final int year = birthDate.year;
    final int month = birthDate.month;
    final int day = birthDate.day;

    final BaziPillar yearPillar = getYearPillar(year, month, day);
    final BaziPillar monthPillar = getMonthPillar(
      month,
      day,
      yearPillar.stemIndex,
      year,
    );
    final BaziPillar dayPillar = getDayPillar(year, month, day);

    BaziPillar? hourPillar;
    String? trueSolarTimeNote;
    int? adjustedHour;

    if (birthHour != null) {
      int tstHour = birthHour;
      int tstMinute = 0;

      if (longitude != null) {
        final tst = applyTrueSolarTime(birthHour, 0, longitude);
        tstHour = tst.hour;
        tstMinute = tst.minute;
        final int offsetMin = tst.offsetMinutes.round();
        final String sign = offsetMin >= 0 ? '+' : '-';
        final int absMin = offsetMin.abs();
        final int stdMeridian = (longitude / 15).round() * 15;
        trueSolarTimeNote =
            '${birthHour.toString().padLeft(2, '0')}:00 → '
            '${tstHour.toString().padLeft(2, '0')}:${tstMinute.toString().padLeft(2, '0')} TST '
            '(bujur ${longitude.toStringAsFixed(2)}°, '
            'meridian standar $stdMeridian°, '
            'koreksi $sign$absMin mnt)';
      }

      hourPillar = getHourPillar(tstHour, dayPillar.stemIndex);
      adjustedHour = tstHour;
    }

    final WuXingBalance balance = calculateWuXingBalance([
      yearPillar,
      monthPillar,
      dayPillar,
      hourPillar,
    ]);

    // Ten Gods — relationship of each pillar stem relative to Day Master
    final int dmIdx = dayPillar.stemIndex;
    final TenGods tenGods = TenGods(
      year: getTenGodId(dmIdx, yearPillar.stemIndex),
      month: getTenGodId(dmIdx, monthPillar.stemIndex),
      hour: hourPillar != null
          ? getTenGodId(dmIdx, hourPillar.stemIndex)
          : null,
    );

    // Day Master Strength
    final String strengthLabel = getDayMasterStrength(
      monthPillar.branchIndex,
      dayPillar.element,
    );
    final favorable = getFavorableElements(dayPillar.element, strengthLabel);
    final DayMasterStrength dmStrength = DayMasterStrength(
      label: strengthLabel,
      yongShen: favorable.yongShen,
      jiShen: favorable.jiShen,
    );

    return BaziChart(
      yearPillar: yearPillar,
      monthPillar: monthPillar,
      dayPillar: dayPillar,
      hourPillar: hourPillar,
      dayMasterId: dayPillar.stemId,
      dayMasterElement: dayPillar.element,
      wuXingBalance: balance,
      tenGods: tenGods,
      dmStrength: dmStrength,
      trueSolarTimeNote: trueSolarTimeNote,
      adjustedHour: adjustedHour,
    );
  }

  // ─── Ten Gods 十神 ──────────────────────────────────────────────────────

  static const Map<String, String> _generates = {
    'kayu': 'api',
    'api': 'tanah',
    'tanah': 'logam',
    'logam': 'air',
    'air': 'kayu',
  };

  static const Map<String, String> _controls = {
    'kayu': 'tanah',
    'tanah': 'air',
    'air': 'api',
    'api': 'logam',
    'logam': 'kayu',
  };

  /// Returns the Ten God id for [targetStemIndex] relative to [dmStemIndex].
  /// IDs match 10gods.json: friend, rob_wealth, eating_god, hurting_officer,
  /// indirect_wealth, direct_wealth, seven_killings, direct_officer,
  /// indirect_resource, direct_resource.
  static String getTenGodId(int dmStemIndex, int targetStemIndex) {
    final String dmEl = stemElements[dmStemIndex];
    final String tgEl = stemElements[targetStemIndex];
    final bool same = (dmStemIndex % 2) == (targetStemIndex % 2);

    if (tgEl == dmEl) return same ? 'friend' : 'rob_wealth';
    if (_generates[dmEl] == tgEl)
      return same ? 'eating_god' : 'hurting_officer';
    if (_controls[dmEl] == tgEl)
      return same ? 'indirect_wealth' : 'direct_wealth';
    if (_controls[tgEl] == dmEl)
      return same ? 'seven_killings' : 'direct_officer';
    if (_generates[tgEl] == dmEl)
      return same ? 'indirect_resource' : 'direct_resource';
    return 'friend'; // unreachable with valid 0–9 stem indices
  }

  /// Returns the Ten God id of the **ruling hidden stem (主氣)** inside
  /// [branchIndex] relative to [dmStemIndex].
  ///
  /// Each Earthly Branch contains 1–3 Cang Gan (藏干 hidden stems).
  /// The first entry is the ruling stem — most influential during the
  /// 5-year branch sub-phase of a Da Yun pillar.
  ///
  /// Example: You 酉 (index 9) → ruling hidden stem Xin (7)
  ///   Day Master Jia Kayu Yang (index 0) → Xin controls Jia
  ///   → direct_officer (正官)
  static String getBranchMainTenGodId(int dmStemIndex, int branchIndex) {
    final int rulingHiddenStem = _branchHiddenStems[branchIndex].first;
    return getTenGodId(dmStemIndex, rulingHiddenStem);
  }

  // ─── Luck Pillars 大運 ──────────────────────────────────────────────────

  // _kSolarTermDates removed — _daysToNearestSolarTerm now uses _jieDays directly.

  /// Builds a [BaziPillar] directly from its 0–59 sexagenary cycle position.
  static BaziPillar _buildPillarFromCycleIndex(int cycleIdx) {
    final int i = ((cycleIdx % 60) + 60) % 60;
    return _buildPillar(i % 10, i % 12);
  }

  /// Returns the number of days between [birth] and the nearest 節 solar term.
  /// [isForward] true → count to the NEXT term; false → count to the PREVIOUS.
  static int _daysToNearestSolarTerm(DateTime birth, bool isForward) {
    final int birthJdn = dateToJdn(birth.year, birth.month, birth.day);
    final List<int> candidates = [];
    for (int yr = birth.year - 1; yr <= birth.year + 1; yr++) {
      for (int termIdx = 0; termIdx < 12; termIdx++) {
        // termIdx 0 = XiaoHan (Jan), 1 = LiChun (Feb), ..., 11 = DaXue (Dec)
        // Use precise _jieDays instead of approximate fixed dates.
        final int month = termIdx + 1;
        final int day = _getJieDay(termIdx, yr);
        candidates.add(dateToJdn(yr, month, day));
      }
    }
    if (isForward) {
      final nexts = candidates.where((j) => j > birthJdn).toList()..sort();
      return nexts.isEmpty ? 30 : nexts.first - birthJdn;
    } else {
      final prevs = candidates.where((j) => j < birthJdn).toList()
        ..sort((a, b) => b.compareTo(a));
      return prevs.isEmpty ? 30 : birthJdn - prevs.first;
    }
  }

  /// Calculates 8 Luck Pillars (大運) from the month pillar sequence.
  ///
  /// Direction rule:
  ///   Male  + Yang year → forward 顺运
  ///   Male  + Yin  year → backward 逆运
  ///   Female + Yang year → backward
  ///   Female + Yin  year → forward
  ///
  /// Starting age = round(days to nearest 節 ÷ 3), clamped to [1, 99].
  static List<LuckPillar> calculateLuckPillars({
    required DateTime birthDate,
    required BaziPillar monthPillar,
    required int yearStemIndex,
    required bool isMale,
    int count = 8,
  }) {
    final bool isYangYear = yearStemIndex % 2 == 0;
    final bool isForward = isMale == isYangYear;

    final int days = _daysToNearestSolarTerm(birthDate, isForward);
    final int startAge = (days / 3).round().clamp(1, 99);

    final int monthCycleIdx = _sexagenaryIndex(
      monthPillar.stemIndex,
      monthPillar.branchIndex,
    );
    final int step = isForward ? 1 : -1;

    return List.generate(count, (i) {
      final int cycleIdx = ((monthCycleIdx + step * (i + 1)) % 60 + 60) % 60;
      return LuckPillar(
        pillar: _buildPillarFromCycleIndex(cycleIdx),
        startAge: startAge + i * 10,
      );
    });
  }

  // ─── Day Master Strength 旺衰 ─────────────────────────────────────────────

  /// Strength matrix: dmElement → scores indexed by branchIndex (0–11).
  /// Score: 4=Sangat Kuat(旺), 3=Kuat(相), 2=Sedang(休), 1=Lemah(囚), 0=Sangat Lemah(死).
  ///
  /// Rule for each (dmElement, branch surface element) cell:
  ///   same element        → 4 旺  |  branch generates DM (生我) → 3 相
  ///   DM generates branch → 2 休  |  DM controls branch  (我克) → 1 囚
  ///   branch controls DM  → 0 死
  ///
  /// Branch surface elements (Zi→Hai):
  ///   air,tanah,kayu,kayu,tanah,api,api,tanah,logam,logam,tanah,air
  /// Canonical source of truth: assets/bazi/bazi-dm-strength-matrix.json
  /// TypeScript equivalent: DM_STRENGTH_MATRIX in aestral-backend/src/bazi.ts
  /// (synced from canonical JSON via scripts/sync-shared-data.js)
  ///
  /// To detect drift in debug builds, call BaziUtils.debugValidateDmMatrix().
  static const Map<String, List<int>> _dmStrengthMatrix = {
    //         Zi  Cou  Yin  Mao  Che  Si   Wu   Wei  She  You  Xu   Hai
    'kayu': [3, 1, 4, 4, 1, 2, 2, 1, 0, 0, 1, 3],
    'api': [0, 2, 3, 3, 2, 4, 4, 2, 1, 1, 2, 0],
    'tanah': [1, 4, 0, 0, 4, 3, 3, 4, 2, 2, 4, 1],
    'logam': [2, 3, 1, 1, 3, 0, 0, 3, 4, 4, 3, 2],
    'air': [4, 0, 2, 2, 0, 1, 1, 0, 3, 3, 0, 4],
  };

  static const List<String> _dmStrengthLabels = [
    'Sangat Lemah', // 0 — 死
    'Lemah', // 1 — 囚
    'Sedang', // 2 — 休
    'Kuat', // 3 — 相
    'Sangat Kuat', // 4 — 旺
  ];

  /// Returns the Day Master strength label based on the month branch season.
  /// Verified: Api DM + Wei(7) month → Sedang(休) ✓
  static String getDayMasterStrength(int monthBranchIndex, String dmElement) {
    final scores = _dmStrengthMatrix[dmElement];
    if (scores == null) return 'Sedang';
    return _dmStrengthLabels[scores[monthBranchIndex]];
  }

  // ─── Favorable / Unfavorable Elements 用神/忌神 ───────────────────────────

  /// Returns yongShen (用神 favorable) and jiShen (忌神 unfavorable) element lists.
  ///
  /// Strong DM (Sangat Kuat/Kuat): needs 我生 (drain) + 克我 (control).
  /// Weak   DM (Sangat Lemah/Lemah): needs 生我 (support) + 比劫 (same).
  /// Sedang: lean toward support (生我 + 比劫).
  static ({List<String> yongShen, List<String> jiShen}) getFavorableElements(
    String dmElement,
    String strength,
  ) {
    final String generates = _generates[dmElement]!;
    final String generatedBy = _generates.entries
        .firstWhere(
          (e) => e.value == dmElement,
          orElse: () => _generates.entries.first,
        ) // W31
        .key;
    final String controlledBy = _controls.entries
        .firstWhere(
          (e) => e.value == dmElement,
          orElse: () => _controls.entries.first,
        ) // W31
        .key;

    switch (strength) {
      case 'Sangat Kuat':
      case 'Kuat':
        return (
          yongShen: [generates, controlledBy],
          jiShen: [generatedBy, dmElement],
        );
      case 'Sangat Lemah':
      case 'Lemah':
        return (
          yongShen: [generatedBy, dmElement],
          jiShen: [controlledBy, generates],
        );
      default: // Sedang
        return (yongShen: [generatedBy, dmElement], jiShen: [controlledBy]);
    }
  }

  // ─── Empty Branches 空亡 ──────────────────────────────────────────────────

  /// Returns the two Empty (空亡 Kongwang) branch indices for the Day Pillar.
  ///
  /// Each 10-day group uses 10 consecutive branches; the remaining 2 are empty.
  /// Formula: group = ci÷10, startBranch = (-2·group mod 12),
  ///          empty = [startBranch+10, startBranch+11] (mod 12).
  /// Example: 丙午 (ci=42, group=4) → empty Yin(2), Mao(3) ✓
  static List<int> getEmptyBranches(BaziPillar dayPillar) {
    final int ci = _sexagenaryIndex(dayPillar.stemIndex, dayPillar.branchIndex);
    final int group = ci ~/ 10;
    final int startBranch = ((-2 * group) % 12 + 12) % 12;
    return [(startBranch + 10) % 12, (startBranch + 11) % 12];
  }

  // ─── Branch Relations 六冲/六合/三合 ──────────────────────────────────────

  /// Six Harmony (六合) pairs keyed as "branchA_branchB" → result element.
  static const Map<String, String> _sixHarmonyResult = {
    '0_1': 'tanah', '1_0': 'tanah', // 子丑合 → Tanah
    '2_11': 'kayu', '11_2': 'kayu', // 寅亥合 → Kayu
    '3_10': 'api', '10_3': 'api', // 卯戌合 → Api
    '4_9': 'logam', '9_4': 'logam', // 辰酉合 → Logam
    '5_8': 'air', '8_5': 'air', // 巳申合 → Air
    '6_7': 'api', '7_6': 'api', // 午未合 → Api
  };

  /// Three Harmony (三合) triads: (branch indices, result element).
  static const List<(List<int>, String)> _threeHarmonyTriads = [
    ([8, 0, 4], 'air'), // 申子辰 → Water
    ([11, 3, 7], 'kayu'), // 亥卯未 → Wood
    ([2, 6, 10], 'api'), // 寅午戌 → Fire
    ([5, 9, 1], 'logam'), // 巳酉丑 → Metal
  ];

  /// Detects Six Clashes (六冲), Six Harmonies (六合), Three Harmonies (三合)
  /// among the given pillars.
  ///
  /// Index convention: 0=Tahun, 1=Bulan, 2=Hari, 3=Jam, 4=Annual(流年).
  /// Null entries (unknown hour) are skipped.
  static BaziRelations detectBranchRelations(List<BaziPillar?> pillars) {
    final clashes = <BaziClash>[];
    final harmonies = <BaziHarmony>[];
    final triads = <BaziTriad>[];

    // Build valid (pillarIndex, branchIndex) list
    final valid = <(int, int)>[];
    for (int i = 0; i < pillars.length; i++) {
      if (pillars[i] != null) valid.add((i, pillars[i]!.branchIndex));
    }

    // Pairwise: Six Clashes + Six Harmonies
    for (int i = 0; i < valid.length; i++) {
      for (int j = i + 1; j < valid.length; j++) {
        final (int idxA, int bA) = valid[i];
        final (int idxB, int bB) = valid[j];

        // Six Clash: branch distance == 6
        if ((bA - bB).abs() == 6) {
          clashes.add(BaziClash(indexA: idxA, indexB: idxB));
        }

        // Six Harmony
        final String? result = _sixHarmonyResult['${bA}_$bB'];
        if (result != null) {
          harmonies.add(
            BaziHarmony(indexA: idxA, indexB: idxB, resultElement: result),
          );
        }
      }
    }

    // Three Harmonies — detect complete (3) and partial (2)
    final presentBranches = valid.map((e) => e.$2).toSet();
    for (final (List<int> trio, String el) in _threeHarmonyTriads) {
      final matched = <int>[];
      for (final branch in trio) {
        for (final (int idx, int b) in valid) {
          if (b == branch) matched.add(idx);
        }
      }
      if (matched.length >= 2) {
        triads.add(
          BaziTriad(
            pillarIndices: matched,
            element: el,
            isComplete:
                matched.length == 3 &&
                trio.every((b) => presentBranches.contains(b)),
          ),
        );
      }
    }

    return BaziRelations(
      clashes: clashes,
      harmonies: harmonies,
      triads: triads,
    );
  }

  // ─── Annual Pillar 流年 ───────────────────────────────────────────────────

  /// Returns the Year Pillar for the current calendar date (今年流年).
  static BaziPillar getCurrentAnnualPillar() {
    final now = DateTime.now();
    return getYearPillar(now.year, now.month, now.day);
  }

  // ─── Nobleman Star 天乙貴人 ───────────────────────────────────────────────

  /// Returns the two Nobleman (天乙貴人) Earthly Branch indices for the Day Stem.
  ///
  /// Traditional Zi Ping assignment:
  ///   Jia(0)/Wu(4)/Geng(6)/Xin(7) → Chou(1), Wei(7)
  ///   Yi(1)/Ji(5)                  → Zi(0),   Shen(8)
  ///   Bing(2)/Ding(3)              → Hai(11), You(9)
  ///   Ren(8)/Gui(9)                → Mao(3),  Si(5)
  static const List<List<int>> _nobelmanTable = [
    [1, 7], // 0 Jia  → Chou, Wei
    [0, 8], // 1 Yi   → Zi,   Shen
    [11, 9], // 2 Bing → Hai,  You
    [11, 9], // 3 Ding → Hai,  You
    [1, 7], // 4 Wu   → Chou, Wei
    [0, 8], // 5 Ji   → Zi,   Shen
    [1, 7], // 6 Geng → Chou, Wei
    [1, 7], // 7 Xin  → Chou, Wei
    [3, 5], // 8 Ren  → Mao,  Si
    [3, 5], // 9 Gui  → Mao,  Si
  ];

  static List<int> getNobleman(int dayStemIndex) =>
      _nobelmanTable[dayStemIndex % 10];
}
