// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkIWh0jxTx97ki2hulRublhv37Nnbqpk',
    appId: '1:367712402581:web:988269ff08940786de2f9c',
    messagingSenderId: '367712402581',
    projectId: 'aestral-ca7ae',
    authDomain: 'aestral-ca7ae.firebaseapp.com',
    storageBucket: 'aestral-ca7ae.firebasestorage.app',
    measurementId: 'G-T2YFSWMTHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNgKFfVjpbo4VnSrtTkkVpxlTlsbHw-QI',
    appId: '1:367712402581:android:16dd79a7bb61b19fde2f9c',
    messagingSenderId: '367712402581',
    projectId: 'aestral-ca7ae',
    storageBucket: 'aestral-ca7ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBudBYOzu4q_GfhA0v6ZhqSmoeVYwD0L3Q',
    appId: '1:367712402581:ios:c83e0f2c8416b688de2f9c',
    messagingSenderId: '367712402581',
    projectId: 'aestral-ca7ae',
    storageBucket: 'aestral-ca7ae.firebasestorage.app',
    iosBundleId: 'com.aestral.aestral',
  );
}
